# <font color=red>**Stemming**</font>

In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import re
import numpy as np

In [2]:
df = pd.read_csv('test17.csv')

In [3]:
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

### TFIDF vectorizer Imbalenced unigram

In [4]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,1), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [6]:
model = MultinomialNB()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("NB acc ",accuracy_score(y_test, pred))

NB acc  0.7518361035948976


In [7]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[   8,  404,    0],
       [   0, 1927,    0],
       [   0,  238,   10]], dtype=int64)

In [8]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.3242736745447165

In [9]:
from sklearn.model_selection import  cross_val_score

In [12]:
cross_val_score(MultinomialNB(),X_train,y_train)

array([0.75807788, 0.75724938, 0.75393538, 0.75642088, 0.75456053])

In [13]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.9166991047100038

In [14]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.3532466854577722

### TFIDF vectorizer balenced unigram

In [15]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [16]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,1), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [17]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))
print("After OverSampling, counts of label '-1': {}".format(sum(y_train_res == -1)))

Using TensorFlow backend.


After OverSampling, the shape of train_X: (19437, 15449)
After OverSampling, the shape of train_y: (19437,) 

After OverSampling, counts of label '1': 6479
After OverSampling, counts of label '0': 6479
After OverSampling, counts of label '-1': 6479


In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [19]:
model = MultinomialNB()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("NB acc ",accuracy_score(y_test, pred))

NB svm acc  0.9038065843621399


In [21]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.9022901931156745

In [22]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.9085804743597096

In [23]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.9033061556285054

In [24]:
from sklearn.model_selection import  cross_val_score
cross_val_score(MultinomialNB(),X_train,y_train)

array([0.88754135, 0.89048144, 0.88129364, 0.88166115, 0.8831312 ])

### TFIDF vectorizer  Imbalenced bigram

In [33]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [34]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(2,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [36]:
model = MultinomialNB()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("NB svm acc ",accuracy_score(y_test, pred))

NB svm acc  0.7456513335910321


In [38]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.29105867435386884

In [39]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

C:\Users\ab\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.47083387145378613

In [40]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.3362236183816083

In [41]:
from sklearn.model_selection import  cross_val_score
cross_val_score(MultinomialNB(),X_train,y_train)

array([0.75476388, 0.75476388, 0.75393538, 0.75476388, 0.75538972])

### TFIDF vectorizer With Imbalencing bigram

In [42]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [43]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(2,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [44]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [46]:
model = MultinomialNB()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("NB acc ",accuracy_score(y_test, pred))

NB acc  0.8389917695473251


In [48]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.8303368560398071

In [49]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.8625511391567701

In [50]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.837785519983818

In [51]:
from sklearn.model_selection import  cross_val_score
cross_val_score(MultinomialNB(),X_train,y_train)

array([0.815509  , 0.81183388, 0.8122014 , 0.8184491 , 0.82175671])

### TFIDF vectorizer  Imbalenced unigram and bigram

In [52]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [53]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [55]:
model = MultinomialNB()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("NB acc ",accuracy_score(y_test, pred))

NB acc  0.7460378817162737


In [57]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.2906833276279989

In [58]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.9152476780185759

In [59]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.336295542332185

In [60]:
from sklearn.model_selection import  cross_val_score
cross_val_score(MultinomialNB(),X_train,y_train)

array([0.75559238, 0.75476388, 0.75393538, 0.75476388, 0.75456053])

### TFIDF vectorizer With Imbalencing unigram and bigram

In [61]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [62]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [63]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [65]:
model = MultinomialNB()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("NB acc ",accuracy_score(y_test, pred))

NB acc  0.9247256515775034


In [67]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.9228582227456338

In [68]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.9311470672542432

In [69]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.9241577134377584

In [70]:
from sklearn.model_selection import  cross_val_score
cross_val_score(MultinomialNB(),X_train,y_train)

array([0.91583976, 0.91473723, 0.91142962, 0.91326718, 0.91179713])