# <font color=red>**Stemming**</font>

In [3]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import svm
import re
import numpy as np

In [3]:
import pandas as pd
df = pd.read_csv('C:/Users/ab/Desktop/test17.csv')

In [4]:
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [5]:
data.head()

text  Sentiment
0                                      binsaab كورو        -1.0
1   صحه سعد حسم جدل بشن خدم جهز جفف يدن قضء يرس ك...        0.0
2   AlsaeedFajer انا حظر كلي لنه منع نشر يرس يقض ...       -1.0
3   رسل رسل لي يدو قطع قلب اخي صلح يدو ل عمي توف ...       -1.0
4   Coronavirus fonds d urgence petites entrepris...        0.0

### TFIDF vectorizer Imbalanced unigram

##### <font color= black >on vectorise les mots par la méthode tf-idf monogram "ngram_range=(1,1)" à l'aide de la TfidfVectorizer </font>

In [5]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,1), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [21]:
model = svm.LinearSVC()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("DS1 svm acc ",accuracy_score(y_test, pred))

DS1 svm acc  0.8078855817549285


In [9]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.5744233257849539

In [11]:
from sklearn.model_selection import  cross_val_score

In [13]:
cross_val_score(LinearSVC(),X_train,y_train)

array([0.7986744 , 0.78956089, 0.8011599 , 0.8069594 , 0.79104478])

In [14]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.8280811877984006

In [15]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.5150507824670306

### TFIDF vectorizer balanced unigram

In [98]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,1), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

#### <font color=black >On équilibre la base de données par over sampling à l'aide de la fonction SMOTE<font>

In [99]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))
print("After OverSampling, counts of label '-1': {}".format(sum(y_train_res == -1)))

After OverSampling, the shape of train_X: (19437, 15449)
After OverSampling, the shape of train_y: (19437,) 

After OverSampling, counts of label '1': 6479
After OverSampling, counts of label '0': 6479
After OverSampling, counts of label '-1': 6479


In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [101]:
model = svm.LinearSVC()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("DS1 svm acc ",accuracy_score(y_test, pred))

DS1 svm acc  0.941358024691358


In [103]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.9403466189962161

In [104]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.9451076080771449

In [105]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.9409234168905788

In [106]:
from sklearn.model_selection import  cross_val_score
cross_val_score(LinearSVC(),X_train,y_train)

array([0.92429254, 0.92686512, 0.93421536, 0.9323778 , 0.92576259])

### TFIDF vectorizer  Imbalanced bigram

#### <font color=black >on vectorise les mots par la méthode tf-idf bigram "ngram_range=(2,2)" à l'aide de la TfidfVectorizer<font>

In [108]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(2,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [110]:
model = svm.LinearSVC()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("DS1 svm acc ",accuracy_score(y_test, pred))

DS1 svm acc  0.7638190954773869


In [46]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[  34,  378,    0],
       [   6, 1919,    2],
       [   3,  222,   23]], dtype=int64)

In [111]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.39373219373219376

In [112]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.8241693055260639

In [113]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.39037155881717345

In [114]:
from sklearn.model_selection import  cross_val_score
cross_val_score(LinearSVC(),X_train,y_train)

array([0.76304888, 0.76719138, 0.76553438, 0.76801988, 0.76533997])

### TFIDF vectorizer  balanced bigram

In [116]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(2,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [117]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

In [118]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [119]:
model = svm.LinearSVC()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("DS1 svm acc ",accuracy_score(y_test, pred))

DS1 svm acc  0.8506515775034293


In [120]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[1925,   12,   15],
       [ 696, 1140,   90],
       [  58,    0, 1896]], dtype=int64)

In [121]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.8436270021258706

In [122]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.8852204228699386

In [123]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.8494618807213093

In [124]:
from sklearn.model_selection import  cross_val_score
cross_val_score(LinearSVC(),X_train,y_train)

array([0.82285924, 0.82285924, 0.81624403, 0.81918412, 0.8246968 ])

### TFIDF vectorizer  Imbalanced unigram and bigram

In [126]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [127]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [128]:
model = svm.LinearSVC()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("DS1 svm acc ",accuracy_score(y_test, pred))

DS1 svm acc  0.8078855817549285


In [129]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[ 118,  290,    4],
       [  14, 1905,    8],
       [  10,  171,   67]], dtype=int64)

In [130]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.5744233257849539

In [131]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.8280811877984006

In [132]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.5150507824670306

In [133]:
from sklearn.model_selection import  cross_val_score
cross_val_score(LinearSVC(),X_train,y_train)

array([0.7986744 , 0.78956089, 0.8011599 , 0.8069594 , 0.79104478])

### TFIDF vectorizer balanced unigram and bigram

In [87]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [88]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [90]:
model = svm.LinearSVC()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("DS1 svm acc ",accuracy_score(y_test, pred))

DS1 svm acc  0.9514746227709191


In [91]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[1928,   12,   12],
       [  51, 1694,  181],
       [  25,    2, 1927]], dtype=int64)

In [92]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.9510089861393851

In [93]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.9542804637142871

In [94]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.9511434009692876

In [95]:
from sklearn.model_selection import  cross_val_score
cross_val_score(LinearSVC(),X_train,y_train)

array([0.94119809, 0.94487321, 0.93642043, 0.93605292, 0.94046307])