# <font color=red>**Stemming**</font>

In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from xgboost import XGBClassifier
import re
import numpy as np

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
df = pd.read_csv('test17.csv')

In [ ]:
data = df
data = data.dropna()
data.isna().sum()

### TFIDF vectorizer Imbalenced unigram

In [4]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,1), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [6]:
model = XGBClassifier()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("XGB acc ",accuracy_score(y_test, pred))

DT acc  0.7711635098569772


In [7]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[ 152,  226,   34],
       [ 111, 1764,   52],
       [  34,  135,   79]], dtype=int64)

In [8]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.5606735502250061

In [9]:
from sklearn.model_selection import  cross_val_score

In [10]:
cross_val_score(XGBClassifier(),X_train,y_train)

array([0.75393538, 0.74979287, 0.78458989, 0.77713339, 0.7628524 ])

In [11]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.6068966792104047

In [12]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.5342976614375429

In [13]:
sentence1 = "رواية لابأس بها رغم الأخطاء"
sentence2 = "رواية رائعة جداً أحببتها كتيراً"
sentence3 = "كتابة سيئة ، بالإضافة إلى أن المستوى رديء للغاية"
sentence4 = "جميل على كل المقايس ، ينصح بقراءتها فلقد أعجبتني ووجدتها ممتعة "
sentence5 = "ضياعٌ للوقت دون أي قيمة مضافة"

In [13]:
txt1 = ["كورو ابس رغم خطء"]
txt2 = ["كورو رءع حبب كتر"]
txt3 = ["Charles Gave Le vrai problème qu idiot"]
txt4 = ["جمل قاس نصح قرء عجب وجد معه"]
txt5 = ["ضيع وقت قيم ضفه"]

In [14]:
txt1 = vectorizer.transform(txt1)
txt2 = vectorizer.transform(txt2)
txt3 = vectorizer.transform(txt3)
txt4 = vectorizer.transform(txt4)
txt5 = vectorizer.transform(txt5)

In [15]:
pred1=model.predict(txt1)
pred2=model.predict(txt2)
pred3=model.predict(txt3)
pred4=model.predict(txt4)
pred5=model.predict(txt5)

In [16]:
print (" the polarity of the 1st sentence is ")
print('\n'.join(map(str, pred1)))
print (" the polarity of the 2nd sentence is ")
print('\n'.join(map(str, pred2)))
print (" the polarity of the 3rd sentence is ")
print('\n'.join(map(str, pred3)))
print (" the polarity of the 4th sentence is ")
print('\n'.join(map(str, pred4)))
print (" the polarity of the 5th sentence is ")
print('\n'.join(map(str, pred5)))

 the polarity of the 1st sentence is 
1.0
 the polarity of the 2nd sentence is 
1.0
 the polarity of the 3rd sentence is 
-1.0
 the polarity of the 4th sentence is 
1.0
 the polarity of the 5th sentence is 
-1.0


### TFIDF vectorizer balenced unigram

In [14]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [15]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,1), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [16]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))
print("After OverSampling, counts of label '-1': {}".format(sum(y_train_res == -1)))

Using TensorFlow backend.


After OverSampling, the shape of train_X: (19437, 15449)
After OverSampling, the shape of train_y: (19437,) 

After OverSampling, counts of label '1': 6479
After OverSampling, counts of label '0': 6479
After OverSampling, counts of label '-1': 6479


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [18]:
model = XGBClassifier()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("XGB acc ",accuracy_score(y_test, pred))

DS1 svm acc  0.8768861454046639


In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[1661,  165,  126],
       [ 140, 1668,  118],
       [  94,   75, 1785]], dtype=int64)

In [20]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.8766496280492441

In [21]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.876824900996693

In [22]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.8768254973466556

In [23]:
from sklearn.model_selection import  cross_val_score
cross_val_score(XGBClassifier(),X_train,y_train)

array([0.86916575, 0.87320838, 0.86108049, 0.86255053, 0.86953326])

### TFIDF vectorizer  Imbalenced bigram

In [24]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [25]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(2,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [27]:
model = XGBClassifier()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("XGB acc ",accuracy_score(y_test, pred))

DS1 svm acc  0.7758020873598763


In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[  71,  324,   17],
       [  27, 1883,   17],
       [  13,  182,   53]], dtype=int64)

In [29]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.4868318728481505

In [30]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.6790103132679018

In [33]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.45440211822772447

In [34]:
from sklearn.model_selection import  cross_val_score
cross_val_score(XGBClassifier(),X_train,y_train)

array([0.78376139, 0.77547639, 0.77796189, 0.78624689, 0.77777778])

### TFIDF vectorizer With Imbalencing bigram

In [35]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [36]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(2,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [37]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [39]:
model = XGBClassifier()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("XGB acc ",accuracy_score(y_test, pred))

DT acc  0.806241426611797


In [40]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[1698,   20,  234],
       [  43, 1065,  818],
       [   7,    8, 1939]], dtype=int64)

In [41]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.8025319874114515

In [42]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.8646854941708368

In [43]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.805053329945748

In [44]:
from sklearn.model_selection import  cross_val_score
cross_val_score(XGBClassifier(),X_train,y_train)

array([0.76332231, 0.76552738, 0.76957001, 0.76111724, 0.78206542])

### TFIDF vectorizer  Imbalenced unigram and bigram

In [45]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [46]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [48]:
model = XGBClassifier()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("XGB acc ",accuracy_score(y_test, pred))

DT acc  0.766524932354078


In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[ 145,  219,   48],
       [ 113, 1752,   62],
       [  47,  115,   86]], dtype=int64)

In [50]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.5550042168698899

In [51]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.5846900978457177

In [52]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.5359670677288632

In [53]:
from sklearn.model_selection import  cross_val_score
cross_val_score(XGBClassifier(),X_train,y_train)

array([0.76884838, 0.75973488, 0.76304888, 0.77464789, 0.76202322])

### TFIDF vectorizer With Imbalencing unigram and bigram

In [54]:
df = pd.read_csv('test17.csv')
data = df
data = data.dropna()
data.isna().sum()

text         0
Sentiment    0
dtype: int64

In [55]:
X = data.text
vectorizer = TfidfVectorizer(ngram_range=(1,2), max_df= 0.7,sublinear_tf = True)
X = vectorizer.fit_transform(X)
y = data.Sentiment

In [56]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 2) 
X_train_res, y_train_res = sm.fit_sample(X, y) 

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_res,y_train_res, test_size=0.3, random_state=42)

In [58]:
model = XGBClassifier()
model.fit(X_train, y_train)
pred=model.predict(X_test)
print("XGB acc ",accuracy_score(y_test, pred))

DT acc  0.8724279835390947


In [59]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[1628,  196,  128],
       [ 135, 1696,   95],
       [  93,   97, 1764]], dtype=int64)

In [60]:
from sklearn.metrics import f1_score
f1_score(y_test, pred,average='macro')

0.8722191728363989

In [61]:
from sklearn.metrics import precision_score
precision_score(y_test, pred,average='macro')

0.8725384915280112

In [62]:
from sklearn.metrics import recall_score
recall_score(y_test, pred,average='macro')

0.8724538238208052

In [63]:
from sklearn.model_selection import  cross_val_score
cross_val_score(XGBClassifier(),X_train,y_train)

array([0.87137082, 0.87431092, 0.85152517, 0.8522602 , 0.86549063])